// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03qlw469w-mJQESjY2TlU55ZMxO-i1F4',
    appId: '1:950700230827:web:e467218a8059fc91888fee',
    messagingSenderId: '950700230827',
    projectId: 'mytselsignlog',
    authDomain: 'mytselsignlog.firebaseapp.com',
    storageBucket: 'mytselsignlog.appspot.com',
    measurementId: 'G-QZXS241VHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXewgXvU-KcFA61FjuU5aBzJFdmIyM37Q',
    appId: '1:950700230827:android:288f0b3b0c6ecc7a888fee',
    messagingSenderId: '950700230827',
    projectId: 'mytselsignlog',
    storageBucket: 'mytselsignlog.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD03qlw469w-mJQESjY2TlU55ZMxO-i1F4',
    appId: '1:950700230827:web:d9723a5338234ff4888fee',
    messagingSenderId: '950700230827',
    projectId: 'mytselsignlog',
    authDomain: 'mytselsignlog.firebaseapp.com',
    storageBucket: 'mytselsignlog.appspot.com',
    measurementId: 'G-36BLVHXZ80',
  );
}
